version: 2.1

orbs:
  # https://circleci.com/orbs/registry/orb/circleci/docker-publish
  docker-publish: circleci/docker-publish@0.1.3

jobs:

  build:
    environment:
      - TZ: "/usr/share/zoneinfo/Canada/Toronto"
      - CONTAINER_NAME: "mgoubran/icvmapper"
    docker:
      - image: docker:18.06.3-ce-git
    working_directory: /tmp/src/iCVMapp3r
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker images
          no_output_timeout: 60m
          command: |
            # Build docker image
            icvmapper_VERSION=$(cat /tmp/src/iCVMapp3r/icvmapper/__init__.py | tr -dc '0-9' | sed 's/./&./g')
            echo "icvmapper version is ${icvmapper_VERSION}"
            e=1 && for i in {1..5}; do
              docker build \
                --rm=false \
                -t ${CONTAINER_NAME} \
                -f /tmp/src/iCVMapp3r/Dockerfile \
                --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
                --build-arg VCS_REF=`git rev-parse --short HEAD` \
                --build-arg VERSION="${CIRCLE_TAG:-$THISVERSION}" . \
              && e=0 && break || sleep 15
            done && [ "$e" -eq "0" ]
      - run:
          name: Run Tests
          no_output_timeout: 2h
          command: |

             echo "Runing tests:"
             docker run --entrypoint bash -it mgoubran/icvmapper -c "icvmapper seg_icv -t1 /src/icvmapp3r/data/test_case/mprage.nii.gz -n 2"

      - store_test_results:
          path: /home/circleci/out/tests


workflows:
  build_and_test:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/

  # This workflow will deploy images on merge to master only
  docker_with_lifecycle:
    jobs:
      - docker-publish/publish:
          image: mgoubran/icvmapper
          tag: latest
          filters:
            branches:
             only: master
          after_build:
            - run:
                name: Publish Docker Tag with icvmapper Version
                command: |
                   docker tag mgoubran/icvmapper:latest mgoubran/icvmapper:0.1.0